### ISSUE TITLE
[Mobile] Template / Example Platform User Shell Application

### ISSUE THREAD

**Issue by IshanDaga** [golain-io/flutter-platform-shell#32]
### Overview
A `good place to start` application for platform users that work well with the starter template across other verticals [Web, Embedded]

### Tasks
- [ ] Rework current example application to include APIs + BLE Mesh sample implementation
- [ ] Add in Casdoor authentication
- [ ] Usage guide / docs
- [ ] walkthrough docs
- [ ] reallocate mac to sharvi
